// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace App.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LandingPage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LandingPage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GoToRedirect()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GoToRedirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserInfoEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserInfoEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserInfoSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserInfoSave);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string LandingPage = "LandingPage";
            public readonly string GoToRedirect = "GoToRedirect";
            public readonly string UserInfoEdit = "UserInfoEdit";
            public readonly string UserInfoSave = "UserInfoSave";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string LandingPage = "LandingPage";
            public const string GoToRedirect = "GoToRedirect";
            public const string UserInfoEdit = "UserInfoEdit";
            public const string UserInfoSave = "UserInfoSave";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_LandingPage s_params_LandingPage = new ActionParamsClass_LandingPage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LandingPage LandingPageParams { get { return s_params_LandingPage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LandingPage
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_GoToRedirect s_params_GoToRedirect = new ActionParamsClass_GoToRedirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GoToRedirect GoToRedirectParams { get { return s_params_GoToRedirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GoToRedirect
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_UserInfoEdit s_params_UserInfoEdit = new ActionParamsClass_UserInfoEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserInfoEdit UserInfoEditParams { get { return s_params_UserInfoEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserInfoEdit
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_UserInfoSave s_params_UserInfoSave = new ActionParamsClass_UserInfoSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserInfoSave UserInfoSaveParams { get { return s_params_UserInfoSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserInfoSave
        {
            public readonly string formData = "formData";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string LandingPage = "LandingPage";
                public readonly string NoPrograms = "NoPrograms";
                public readonly string UserInfoEdit = "UserInfoEdit";
            }
            public readonly string LandingPage = "~/Views/Home/LandingPage.cshtml";
            public readonly string NoPrograms = "~/Views/Home/NoPrograms.cshtml";
            public readonly string UserInfoEdit = "~/Views/Home/UserInfoEdit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : App.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.Home.UserIndexViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(App.ViewModels.Home.UserIndexViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            IndexOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void LandingPageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.Home.IndexViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult LandingPage(App.ViewModels.Home.IndexViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LandingPage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            LandingPageOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void GoToRedirectOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.Home.IndexViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult GoToRedirect(App.ViewModels.Home.IndexViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GoToRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            GoToRedirectOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void UserInfoEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.Home.UserInfoEditViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserInfoEdit(App.ViewModels.Home.UserInfoEditViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserInfoEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            UserInfoEditOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void UserInfoSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.Home.UserInfoEditViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserInfoSave(App.ViewModels.Home.UserInfoEditViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserInfoSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            UserInfoSaveOverride(callInfo, formData);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
