// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace App.Controllers
{
    public partial class PersonSuggestionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PersonSuggestionController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PersonSuggestionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SuggestionNew()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionNew);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SuggestionNewSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionNewSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SuggestionEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SuggestionEditSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionEditSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SuggestionDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionDelete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PersonSuggestionController Actions { get { return MVC.PersonSuggestion; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PersonSuggestion";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PersonSuggestion";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SuggestionNew = "SuggestionNew";
            public readonly string SuggestionNewSave = "SuggestionNewSave";
            public readonly string SuggestionEdit = "SuggestionEdit";
            public readonly string SuggestionEditSave = "SuggestionEditSave";
            public readonly string SuggestionDelete = "SuggestionDelete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SuggestionNew = "SuggestionNew";
            public const string SuggestionNewSave = "SuggestionNewSave";
            public const string SuggestionEdit = "SuggestionEdit";
            public const string SuggestionEditSave = "SuggestionEditSave";
            public const string SuggestionDelete = "SuggestionDelete";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_SuggestionNew s_params_SuggestionNew = new ActionParamsClass_SuggestionNew();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuggestionNew SuggestionNewParams { get { return s_params_SuggestionNew; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuggestionNew
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_SuggestionNewSave s_params_SuggestionNewSave = new ActionParamsClass_SuggestionNewSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuggestionNewSave SuggestionNewSaveParams { get { return s_params_SuggestionNewSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuggestionNewSave
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_SuggestionEdit s_params_SuggestionEdit = new ActionParamsClass_SuggestionEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuggestionEdit SuggestionEditParams { get { return s_params_SuggestionEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuggestionEdit
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_SuggestionEditSave s_params_SuggestionEditSave = new ActionParamsClass_SuggestionEditSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuggestionEditSave SuggestionEditSaveParams { get { return s_params_SuggestionEditSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuggestionEditSave
        {
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_SuggestionDelete s_params_SuggestionDelete = new ActionParamsClass_SuggestionDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuggestionDelete SuggestionDeleteParams { get { return s_params_SuggestionDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuggestionDelete
        {
            public readonly string formData = "formData";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string NoPrograms = "NoPrograms";
                public readonly string SuggestionAppendixEdit = "SuggestionAppendixEdit";
                public readonly string SuggestionEdit = "SuggestionEdit";
                public readonly string SuggestionNew = "SuggestionNew";
            }
            public readonly string Index = "~/Views/PersonSuggestion/Index.cshtml";
            public readonly string NoPrograms = "~/Views/PersonSuggestion/NoPrograms.cshtml";
            public readonly string SuggestionAppendixEdit = "~/Views/PersonSuggestion/SuggestionAppendixEdit.cshtml";
            public readonly string SuggestionEdit = "~/Views/PersonSuggestion/SuggestionEdit.cshtml";
            public readonly string SuggestionNew = "~/Views/PersonSuggestion/SuggestionNew.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PersonSuggestionController : App.Controllers.PersonSuggestionController
    {
        public T4MVC_PersonSuggestionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.IndexViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(App.ViewModels.PersonSuggestion.IndexViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            IndexOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void SuggestionNewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.SuggestionNewViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult SuggestionNew(App.ViewModels.PersonSuggestion.SuggestionNewViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionNew);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SuggestionNewOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void SuggestionNewSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.SuggestionNewViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult SuggestionNewSave(App.ViewModels.PersonSuggestion.SuggestionNewViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionNewSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SuggestionNewSaveOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void SuggestionEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.SuggestionEditViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult SuggestionEdit(App.ViewModels.PersonSuggestion.SuggestionEditViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SuggestionEditOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void SuggestionEditSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.SuggestionEditViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult SuggestionEditSave(App.ViewModels.PersonSuggestion.SuggestionEditViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionEditSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SuggestionEditSaveOverride(callInfo, formData);
            return callInfo;
        }

        [NonAction]
        partial void SuggestionDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, App.ViewModels.PersonSuggestion.SuggestionDeleteViewModel formData);

        [NonAction]
        public override System.Web.Mvc.ActionResult SuggestionDelete(App.ViewModels.PersonSuggestion.SuggestionDeleteViewModel formData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuggestionDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SuggestionDeleteOverride(callInfo, formData);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
