// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace App.Controllers
{
    public partial class UtilityController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilityController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UtilityController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetChapters()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetChapters);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetFields()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFields);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilityController Actions { get { return MVC.Utility; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Utility";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Utility";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetChapters = "GetChapters";
            public readonly string GetFields = "GetFields";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetChapters = "GetChapters";
            public const string GetFields = "GetFields";
        }


        static readonly ActionParamsClass_GetChapters s_params_GetChapters = new ActionParamsClass_GetChapters();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetChapters GetChaptersParams { get { return s_params_GetChapters; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetChapters
        {
            public readonly string versionId = "versionId";
        }
        static readonly ActionParamsClass_GetFields s_params_GetFields = new ActionParamsClass_GetFields();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFields GetFieldsParams { get { return s_params_GetFields; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFields
        {
            public readonly string chapterId = "chapterId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UtilityController : App.Controllers.UtilityController
    {
        public T4MVC_UtilityController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetChaptersOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string versionId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetChapters(string versionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetChapters);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "versionId", versionId);
            GetChaptersOverride(callInfo, versionId);
            return callInfo;
        }

        [NonAction]
        partial void GetFieldsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string chapterId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetFields(string chapterId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFields);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chapterId", chapterId);
            GetFieldsOverride(callInfo, chapterId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
