//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APTIFYEntities : DbContext
    {
        public APTIFYEntities()
            : base("name=APTIFYEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwACSNtdsChapter> vwACSNtdsChapter { get; set; }
        public virtual DbSet<vwACSNtdsExternalStatusType> vwACSNtdsExternalStatusType { get; set; }
        public virtual DbSet<vwACSNtdsInternalStatusType> vwACSNtdsInternalStatusType { get; set; }
        public virtual DbSet<vwACSNtdsProgram> vwACSNtdsProgram { get; set; }
        public virtual DbSet<vwACSNtdsUserInfo> vwACSNtdsUserInfo { get; set; }
        public virtual DbSet<vwACSNtdsVersion> vwACSNtdsVersion { get; set; }
        public virtual DbSet<vwACSNtdsSuggestion> vwACSNtdsSuggestion { get; set; }
        public virtual DbSet<vwACSNtdsPersonSuggestions> vwACSNtdsPersonSuggestions { get; set; }
        public virtual DbSet<vwACSNtdsFieldType> vwACSNtdsFieldType { get; set; }
        public virtual DbSet<vwACSNtdsField> vwACSNtdsField { get; set; }
    }
}
