//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACSNtdsPersonSuggestions
    {
        public int ID { get; set; }
        public int PersonId { get; set; }
        public string PersonId_AcsMailName { get; set; }
        public string NewFieldName { get; set; }
        public string Definition { get; set; }
        public string FieldValues { get; set; }
        public string AdditionalInformation { get; set; }
        public string DataSourceHierarchy { get; set; }
        public string AssociatedEditChecks { get; set; }
        public string RationaleForChange { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string ChapterName { get; set; }
        public string VersionName { get; set; }
        public int ExternalStatusTypeId { get; set; }
        public string ExternalStatusTypeId_Name { get; set; }
        public int InternalStatusTypeId { get; set; }
        public string InternalStatusTypeId_Name { get; set; }
        public string FieldName { get; set; }
        public int FieldId { get; set; }
        public Nullable<int> NtdsChapterId { get; set; }
        public Nullable<int> NtdsVersionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> NtdsFieldTypeId { get; set; }
        public string NtdsFieldTypeId_Name { get; set; }
        public Nullable<bool> IsAppendix { get; set; }
    }
}
