//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACSNtdsField
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int NtdsFieldSequence { get; set; }
        public int NtdsChapterId { get; set; }
        public int NtdsChapterId_Name { get; set; }
        public int NtdsChapterId_VersionId { get; set; }
        public Nullable<int> NtdsFieldTypeId { get; set; }
        public string NtdsFieldTypeId_Name { get; set; }
    }
}
