//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACSNtdsChapter
    {
        public int ID { get; set; }
        public int ChapterNumber { get; set; }
        public string ChapterName { get; set; }
        public string Description { get; set; }
        public string ChapterNumberName { get; set; }
        public int NtdsVersionId { get; set; }
        public string NtdsVersionId_Name { get; set; }
        public bool IsAppendix { get; set; }
    }
}
