//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACSNtdsUserInfo
    {
        public int ID { get; set; }
        public int PersonId { get; set; }
        public string PersonId_ACSMailName { get; set; }
        public string UserType { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> NTDBId { get; set; }
    }
}
